import type { paths, components } from "./schema"; // generated by openapi-typescript

// Schema Obj
type User = components["schemas"]["User"];

// // Path params
// type EndpointParams = paths["/my/endpoint"]["parameters"];

// // Response obj
// type SuccessResponse =
//   paths["/my/endpoint"]["get"]["responses"][200]["content"]["application/json"]["schema"];
// type ErrorResponse =
//   paths["/my/endpoint"]["get"]["responses"][500]["content"]["application/json"]["schema"];